page_conf =[{"id": 'page1', "img_name": 'page1.png', "audio_name": 'page1.wav', "next_page":2, 'que_id':'', 'que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page2', "img_name": 'page2.png', "audio_name": 'page2.wav', "next_page":3, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page3', "img_name": 'page3.png', "audio_name": 'page3.wav', "next_page":4, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page4', "img_name": 'page4.png', "audio_name": 'page4.wav', "next_page":5, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page5', "img_name": 'page5.png', "audio_name": 'page5.wav', "next_page":6, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page6', "img_name": 'page6.png', "audio_name": 'page6.wav', "next_page":7, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page7', "img_name": 'page7.png', "audio_name": 'page7.wav', "next_page":8, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page8', "img_name": 'page8.png', "audio_name": 'page8.wav', "next_page":9, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page9', "img_name": 'page9.png', "audio_name": 'page9.wav', "next_page":10, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page10', "img_name": 'page10.png', "audio_name": 'page10.wav', "next_page":11, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page11', "img_name": 'page11.png', "audio_name": 'page11.wav', "next_page":12, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page12', "img_name": 'page12.png', "audio_name": 'page12.wav', "next_page":13, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page13', "img_name": 'page13.png', "audio_name": 'page13.wav', "next_page":14, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]}, 
            {"id": 'page14', "img_name": 'page14.png', "audio_name": 'page14.wav', "next_page":15, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page15', "img_name": 'page15.png', "audio_name": 'page15.wav', "next_page":16, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},  
            {"id": 'page16', "img_name": 'page16.png', "audio_name": 'page16.wav', "next_page":17, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page17', "img_name": 'page17.png', "audio_name": 'page17.wav', "next_page":18, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page18', "img_name": 'page18.png', "audio_name": 'page18.wav', "next_page":19, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page19', "img_name": 'page19.png', "audio_name": 'page19.wav', "next_page":20, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]}, 
            {"id": 'page20', "img_name": 'page20.png', "audio_name": 'page20.wav', "next_page":21, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page21', "img_name": 'page21.png', "audio_name": 'page21.wav', "next_page":22, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page22', "img_name": 'page22.png', "audio_name": 'page22.wav', "next_page":23, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page23', "img_name": 'page23.png', "audio_name": 'page23.wav', "next_page":24, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]}, 
            {"id": 'page24', "img_name": 'page24.png', "audio_name": 'page24.wav', "next_page":25, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page25', "img_name": 'page25.png', "audio_name": 'page25.wav', "next_page":1, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]}        
            ]
page_conf_nemo =[{"id": 'page1', "img_name": 'page1.png', "audio_name": 'page1.wav', "next_page":2, 'que_id':'', 'que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page2', "img_name": 'page2.png', "audio_name": 'page2.wav', "next_page":3, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page3', "img_name": 'page3.png', "audio_name": 'page3.wav', "next_page":4, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page4', "img_name": 'page4.png', "audio_name": 'page4.wav', "next_page":5, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page5', "img_name": 'page5.png', "audio_name": 'page5.wav', "next_page":1, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]}
]
page_conf_baba =[{"id": 'page1', "img_name": 'barbabravo.gif', "audio_name": 'p1.wav', "next_page":2, 'que_id':'', 'que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page2', "img_name": 'barbabravo.gif', "audio_name": 'p2.wav', "next_page":3, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page3', "img_name": 'barbabravo.gif', "audio_name": 'p3.wav', "next_page":4, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page4', "img_name": 'barbabravo.gif', "audio_name": 'p4.wav', "next_page":5, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page5', "img_name": 'barbabravo.gif', "audio_name": 'p5.wav', "next_page":6, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
             {"id": 'page6', "img_name": 'barbabravo.gif', "audio_name": 'p6.wav', "next_page":7, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page7', "img_name": 'barbabravo.gif', "audio_name": 'p7.wav', "next_page":8, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page8', "img_name": 'barbabravo.gif', "audio_name": 'p8.wav', "next_page":1, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]}           
]
page_conf_firetruck =[{"id": 'page1', "img_name": 'p0.png', "audio_name": 'p1.wav', "next_page":2, 'que_id':'', 'que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page2', "img_name": 'p0.png', "audio_name": 'p2.wav', "next_page":3, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page3', "img_name": 'p0.png', "audio_name": 'p3.wav', "next_page":4, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page4', "img_name": 'p0.png', "audio_name": 'p4.wav', "next_page":5, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page5', "img_name": 'p0.png', "audio_name": 'p5.wav', "next_page":6, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
             {"id": 'page6', "img_name": 'p0.png', "audio_name": 'p6.wav', "next_page":7, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page7', "img_name": 'p0.png', "audio_name": 'p7.wav', "next_page":8, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page8', "img_name": 'p0.png', "audio_name": 'p8.wav', "next_page":9, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},   
            {"id": 'page9', "img_name": 'p0.png', "audio_name": 'p9.wav', "next_page":10, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
             {"id": 'page10', "img_name": 'p0.png', "audio_name": 'p10.wav', "next_page":11, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page11', "img_name": 'p0.png', "audio_name": 'p11.wav', "next_page":12, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page12', "img_name": 'p0.png', "audio_name": 'p12.wav', "next_page":13, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},   
            {"id": 'page13', "img_name": 'p0.png', "audio_name": 'p13.wav', "next_page":1, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]}     
]
page_conf_pigeon =[{"id": 'page1', "img_name": 'p1.png', "audio_name": 'p1.wav', "next_page":2, 'que_id':'', 'que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page2', "img_name": 'p2.png', "audio_name": 'p2.wav', "next_page":3, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page3', "img_name": 'p3.png', "audio_name": 'p3.wav', "next_page":4, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page4', "img_name": 'p4.png', "audio_name": 'p4.wav', "next_page":5, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page5', "img_name": 'p5.png', "audio_name": 'p5.wav', "next_page":6, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
             {"id": 'page6', "img_name": 'p6.png', "audio_name": 'p6.wav', "next_page":7, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page7', "img_name": 'p7.png', "audio_name": 'p7.wav', "next_page":8, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page8', "img_name": 'p8.png', "audio_name": 'p8.wav', "next_page":9, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},   
            {"id": 'page9', "img_name": 'p9.png', "audio_name": 'p9.wav', "next_page":10, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
             {"id": 'page10', "img_name": 'p10.png', "audio_name": 'p10.wav', "next_page":11, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page11', "img_name": 'p11.png', "audio_name": 'p11.wav', "next_page":12, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page12', "img_name": 'p12.png', "audio_name": 'p12.wav', "next_page":13, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},   
            {"id": 'page13', "img_name": 'p13.png', "audio_name": 'p13.wav', "next_page":14, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
             {"id": 'page14', "img_name": 'p14.png', "audio_name": 'p14.wav', "next_page":15, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page15', "img_name": 'p15.png', "audio_name": 'p15.wav', "next_page":16, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page16', "img_name": 'p16.png', "audio_name": 'p16.wav', "next_page":17, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},   
            {"id": 'page17', "img_name": 'p17.png', "audio_name": 'p17.wav', "next_page":1, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
]
page_conf_worm =[{"id": 'page1', "img_name": 'p1.png', "audio_name": 'p1.wav', "next_page":2, 'que_id':'', 'que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page2', "img_name": 'p2.png', "audio_name": 'p2.wav', "next_page":3, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page3', "img_name": 'p3.png', "audio_name": 'p3.wav', "next_page":4, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page4', "img_name": 'p4.png', "audio_name": 'p4.wav', "next_page":5, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page5', "img_name": 'p5.png', "audio_name": 'p5.wav', "next_page":6, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
             {"id": 'page6', "img_name": 'p6.png', "audio_name": 'p6.wav', "next_page":7, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page7', "img_name": 'p7.png', "audio_name": 'p7.wav', "next_page":8, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page8', "img_name": 'p8.png', "audio_name": 'p8.wav', "next_page":9, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},   
            {"id": 'page9', "img_name": 'p9.png', "audio_name": 'p9.wav', "next_page":10, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
             {"id": 'page10', "img_name": 'p10.png', "audio_name": 'p10.wav', "next_page":11, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page11', "img_name": 'p11.png', "audio_name": 'p11.wav', "next_page":12, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},
            {"id": 'page12', "img_name": 'p12.png', "audio_name": 'p12.wav', "next_page":13, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]},   
            {"id": 'page13', "img_name": 'p13.png', "audio_name": 'p13.wav', "next_page":1, 'que_id':'','que_audio':'', 'ans_audio':'', 'count_max': 0, 'ans_keys':[]}
]
